apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    web: nginx
spec:
  serviceAccountName: my-service-account
  containers:
    - name: nginx
      image: 779882487479.dkr.ecr.us-east-1.amazonaws.com/tentativafc-br:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
