apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: { { .Values.name } }
  namespace: { { .Release.Namespace } }
spec:
  serviceRef:
    name: istio-ingressgateway # route traffic to the awesome-service
    port: 80
  targetGroupARN: { { .Values.tg_80_arn } }
  targetType: { { .Values.target_type } } # instance for ec2, ip for fargate
  networking:
    ingress:
      - from:
          - ipBlock:
              cidr: 0.0.0.0/0 # subnet-1 cidr
        ports:
          - protocol: TCP # Allow all TCP traffic from ALB SG
            port: 31381 # NodePort from Istio Ingress
