apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: my-tgb-80-nlb
  namespace: istio-system
spec:
  # nodeSelector:
  #   matchLabels:
  #     foo: bar
  serviceRef:
    name: istio-ingressgateway # route traffic to the awesome-service
    # port: 31381
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:779882487479:targetgroup/testing-istio-80-31381/3b15ff9707242d31
  targetType: instance
  networking:
    ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0 # subnet-1 cidr
      ports:
      - protocol: TCP # Allow all TCP traffic from ALB SG    
        port: 31381
        # port: 80