apiVersion: v1
clusters:
  - cluster:
      server: https://D4302F315F0154F26293229717614DDD.yl4.us-east-1.eks.amazonaws.com
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EWXhPREV3TVRNMU9Gb1hEVE14TURZeE5qRXdNVE0xT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGJBCmNMajlsWk1Sb0FHSk5RY2p5Yk44eUxtYVJxdFNPT29OS2tjREI5dTFaeTNJdjFIWnZlZnl3NVNSMm9ZWlN5MWgKL3pxbC9MVkUxNkFtRTlFNmdRcVJWaVI1RUgvVEZPVEdmVVVIb2p2UVYwYlg4WDZESzFIM0ZJRFpCemc0a0dTMwozMEFWK1RBOHFPNlIySTl5MlczTDJNdlFlcXJGWlFqNXp1TUlJTzdtbTZKMERHdUpYRENRNDcwb0xxb1lEY2ZZCnROR0xOV0Z6UXQ5Q0pxWWZBUVNlM2hxZjV5M2lyaHZWVGhFenRuN05FVXc2RnNSZHlVazRXdE14UE5yc2VGbTYKZHhrclJrNk9BSU1wbGhYTGNKV0taMHBOQUMyK2xpQTZuekowUTJZRVlPTXFaQk05cU8yUDdyNGhPQ2RTWDhUYwplcWFRNzdmbWlmbXpUWTEvTkI4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGVytVVkk1QktTS0I1d2ZVam1taElENDFZbnVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDbXgrcnJwVVZBdnJJbndUdGpWWHlEbVNSODFMWnhPVW5mODVWOFlYWkdnNUJSWVJVUgpQUndtUEpyQ2s3WlVwaDFJZWQvQ09hNndXaWJvWUdkamRmbkYzWEkyak1NdlVlVlkyaFJOdzBZcHFBSzhQNGh1CnhkbjdrY0xQYTJCb0lGS09qc3crL2FnWTIxM2w1Rmxwc0Z6ZzNlOElNREwxNkp0NDNwWEszL0UyV0pCS2ZqdncKQitycllNc004T014Slkxd2dyMktOUjZOcmhLZlh2Ymp4RnUzdURkLzE3YUFLLytKQXQvc1BDR244bGltZzdXNQptTjFyZ2pQb1ZoeU5VeE5wNldvNXFvOVFXSEJLb085NDZVUnp6c05VZWlCNXBzKy9OS0ZyUi9CN1EzRG51L0JCCkkwbXk2ZlFPNVMzdDNCMkxnNm9oWnVhNjBIcnFMS3lRU0ExVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: aws
current-context: aws
kind: Config
preferences: {}
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws-iam-authenticator
        args:
          - "token"
          - "-i"
          - "eks-demo"
          # - "-r"
          # - "<role-arn>"
        # env:
        # - name: AWS_PROFILE
        #   value: "<aws-profile>"
